# Generated by Django 6.0.7 on 2026-08-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=250, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите содержимое статьи', verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('views_counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
