# Generated by Django 6.0.7 on 2026-09-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'В продаже'), ('out_of-stock', 'Нет в наличии'), ('discontinued', 'Снят с продажи')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
