# Generated by Django 6.0.7 on 2026-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'В продаже'), ('out_of_stock', 'Нет в наличии'), ('discontinued', 'Снят с продажи')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
